# Generated by Django 2.1.2 on 2018-10-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='no image', upload_to='%y/%m/%d/orig'),
            preserve_default=False,
        ),
    ]
